const translations={
en:{navHome:'Home',navGames:'Games',navAbout:'About',heroEyebrow:'THE CASE OF THE LOST BOOK',heroTitle:'Welcome to English Adventure City',heroText:'Complete three missions, solve the mystery and return the Book of Knowledge to the city.',startAdventure:'Start adventure',missionLabel:'THREE CHAPTERS — ONE STORY',chooseMission:'Choose your mission',wordText:'Restore the missing dictionary pages by typing vocabulary words and collecting clues.',grammarText:'Defend Grammar Academy from incorrect sentences and survive four attack waves.',sentenceText:'Investigate five locations, decode messages and reveal who hid the Book of Knowledge.',play:'Play',howToPlay:'How to play',aboutLabel:'ABOUT THE PROJECT',aboutTitle:'English practice through investigation and adventure',aboutText:'Each mission has three difficulty levels, sound effects, scores, clues and a complete story ending.',briefing:'MISSION BRIEFING',startMission:'Start mission',featureMissions:'Exciting missions',featureCrystals:'Knowledge crystals',featureLanguages:'Interface languages',featureStory:'Connected story'},
ru:{navHome:'Главная',navGames:'Игры',navAbout:'О проекте',heroEyebrow:'ДЕЛО О ПРОПАВШЕЙ КНИГЕ',heroTitle:'Добро пожаловать в English Adventure City',heroText:'Пройдите три миссии, раскройте тайну и верните городу Книгу знаний.',startAdventure:'Начать приключение',missionLabel:'ТРИ ГЛАВЫ — ОДНА ИСТОРИЯ',chooseMission:'Выберите миссию',wordText:'Восстановите страницы словаря: печатайте слова и собирайте улики.',grammarText:'Защитите Академию грамматики от неправильных предложений и выдержите четыре волны.',sentenceText:'Исследуйте пять локаций, расшифруйте сообщения и найдите того, кто спрятал Книгу знаний.',play:'Играть',howToPlay:'Как играть',aboutLabel:'О ПРОЕКТЕ',aboutTitle:'Английский через расследование и приключение',aboutText:'В каждой миссии есть три уровня сложности, звуки, очки, улики и законченный сюжет.',briefing:'ИНСТРУКТАЖ',startMission:'Начать миссию',featureMissions:'Захватывающие миссии',featureCrystals:'Кристаллы знаний',featureLanguages:'Языки интерфейса',featureStory:'Единый сюжет'},
be:{navHome:'Галоўная',navGames:'Гульні',navAbout:'Аб праекце',heroEyebrow:'СПРАВА АБ ЗНІКЛАЙ КНІЗЕ',heroTitle:'Сардэчна запрашаем у English Adventure City',heroText:'Прайдзіце тры місіі, раскрыйце таямніцу і вярніце Кнігу ведаў.',startAdventure:'Пачаць прыгоду',missionLabel:'ТРИ РАЗДЗЕЛЫ — АДНА ГІСТОРЫЯ',chooseMission:'Выберыце місію',wordText:'Аднавіце старонкі слоўніка: друкуйце словы і збірайце доказы.',grammarText:'Абараніце Акадэмію граматыкі і вытрымайце чатыры хвалі.',sentenceText:'Даследуйце пяць месцаў, расшыфруйце паведамленні і знайдзіце вінаватага.',play:'Гуляць',howToPlay:'Як гуляць',aboutLabel:'АБ ПРАЕКЦЕ',aboutTitle:'Англійская праз расследаванне і прыгоды',aboutText:'Кожная місія мае тры ўзроўні складанасці, гукі, балы, доказы і фінал.',briefing:'ІНСТРУКТАЖ',startMission:'Пачаць місію',featureMissions:'Захапляльныя місіі',featureCrystals:'Крышталі ведаў',featureLanguages:'Мовы інтэрфейсу',featureStory:'Адзіны сюжэт'},
zh:{navHome:'首页',navGames:'游戏',navAbout:'关于',heroEyebrow:'失踪之书案件',heroTitle:'欢迎来到英语冒险城',heroText:'完成三项任务，解开谜团，把知识之书带回城市。',startAdventure:'开始冒险',missionLabel:'三个章节，一个故事',chooseMission:'选择任务',wordText:'输入词汇并收集线索，恢复丢失的词典页面。',grammarText:'保护语法学院，击退四波错误句子。',sentenceText:'调查五个地点，解码信息，找出藏起知识之书的人。',play:'开始',howToPlay:'游戏规则',aboutLabel:'关于项目',aboutTitle:'通过调查与冒险练习英语',aboutText:'每项任务都有三个难度、音效、分数、线索和完整结局。',briefing:'任务说明',startMission:'开始任务',featureMissions:'精彩任务',featureCrystals:'知识水晶',featureLanguages:'界面语言',featureStory:'完整故事'},
ar:{navHome:'الرئيسية',navGames:'الألعاب',navAbout:'عن المشروع',heroEyebrow:'قضية الكتاب المفقود',heroTitle:'مرحبًا بك في مدينة مغامرات الإنجليزية',heroText:'أكمل ثلاث مهام واكشف اللغز وأعد كتاب المعرفة إلى المدينة.',startAdventure:'ابدأ المغامرة',missionLabel:'ثلاثة فصول — قصة واحدة',chooseMission:'اختر مهمتك',wordText:'استعد صفحات القاموس بكتابة الكلمات وجمع الأدلة.',grammarText:'دافع عن أكاديمية القواعد واصمد أمام أربع موجات.',sentenceText:'حقق في خمسة مواقع وفك الرسائل واكتشف من أخفى الكتاب.',play:'العب',howToPlay:'طريقة اللعب',aboutLabel:'عن المشروع',aboutTitle:'تعلّم الإنجليزية من خلال التحقيق والمغامرة',aboutText:'لكل مهمة ثلاثة مستويات صعوبة ومؤثرات صوتية ونقاط وأدلة ونهاية كاملة.',briefing:'تعليمات المهمة',startMission:'ابدأ المهمة',featureMissions:'مهام مشوقة',featureCrystals:'بلورات المعرفة',featureLanguages:'لغات الواجهة',featureStory:'قصة مترابطة'}};

const labels={en:'English',ru:'Русский',be:'Беларуская',zh:'中文',ar:'العربية'};
const rules={
word:{title:'Word Sprint',url:'games/word-sprint.html',items:['Choose Junior, Explorer or Expert.','Type each English word exactly as shown.','Correct answers reveal clues and increase your score.','Finish four missions to recover the dictionary.']},
grammar:{title:'Grammar Defender',url:'games/grammar-defender.html',items:['Choose a difficulty level.','Read the flying sentence targets.','Select only the grammatically correct sentence.','Protect the city through four attack waves.']},
sentence:{title:'Sentence Detective',url:'games/sentence-detective.html',items:['Choose a difficulty level.','Investigate five locations.','Arrange words to restore secret messages.','Use the clues to solve the final mystery.']}
};

let currentLang=localStorage.getItem('typegame_lang')||'en';
let soundOn=localStorage.getItem('typegame_sound')!=='off';
const clickSound=document.getElementById('clickSound');

function applyLang(lang){
currentLang=lang;localStorage.setItem('typegame_lang',lang);
document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
document.body.classList.toggle('rtl',lang==='ar');
document.getElementById('languageLabel').textContent=labels[lang];
document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});
}
function click(){if(soundOn){clickSound.currentTime=0;clickSound.play().catch(()=>{})}}
document.getElementById('languageButton').onclick=()=>{click();document.getElementById('languageMenu').classList.toggle('open')};
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{applyLang(b.dataset.lang);document.getElementById('languageMenu').classList.remove('open');click()});
document.getElementById('soundToggle').onclick=()=>{soundOn=!soundOn;localStorage.setItem('typegame_sound',soundOn?'on':'off');document.getElementById('soundToggle').textContent=soundOn?'SOUND ON':'SOUND OFF';click()};
document.querySelectorAll('.rules').forEach(btn=>btn.onclick=()=>{click();const r=rules[btn.dataset.game];document.getElementById('modalTitle').textContent=r.title;document.getElementById('modalText').innerHTML='<ul>'+r.items.map(x=>'<li>'+x+'</li>').join('')+'</ul>';document.getElementById('modalPlay').href=r.url;document.getElementById('rulesModal').classList.add('open')});
document.getElementById('modalClose').onclick=()=>document.getElementById('rulesModal').classList.remove('open');
document.querySelector('.modal-backdrop').onclick=()=>document.getElementById('rulesModal').classList.remove('open');
document.querySelectorAll('a,button').forEach(el=>el.addEventListener('click',()=>{if(!el.classList.contains('language-current'))click()}));
window.addEventListener('load',()=>setTimeout(()=>document.getElementById('intro').classList.add('hide'),1100));
applyLang(currentLang);
document.getElementById('soundToggle').textContent=soundOn?'SOUND ON':'SOUND OFF';